### ISSUE TITLE
Requiring module 'NativeModules' by name - arguments[0].indexOf is undefined

### ISSUE THREAD

**Issue by airandfingers** [jhen0409/rn-host-detect#9]
I just got the issue described in and fixed by https://github.com/jhen0409/rn-host-detect/pull/8: a library I'm using called `console.warn` with an `Error`, and your library's `console.warn` polyfill crashes on non-string first arguments.

Here's the full text of the error, for reference:

> TypeError: arguments[0].indexOf is not a function. (In 'arguments[0].indexOf('Requiring module \'NativeModules\' by name')', 'arguments[0].indexOf' is undefined)

**Comment by jhen0409** [comment]
Fixed by #8.
